// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeBooker.DataAccess.Data;

#nullable disable

namespace OfficeBooker.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfficeBooker.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int>("OfficeNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            Equipment = "[]",
                            FloorNumber = 0,
                            OfficeNumber = 101
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 8,
                            Equipment = "[]",
                            FloorNumber = 0,
                            OfficeNumber = 102
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 12,
                            Equipment = "[]",
                            FloorNumber = 0,
                            OfficeNumber = 103
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 10,
                            Equipment = "[]",
                            FloorNumber = 1,
                            OfficeNumber = 201
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 15,
                            Equipment = "[]",
                            FloorNumber = 1,
                            OfficeNumber = 202
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 10,
                            Equipment = "[]",
                            FloorNumber = 1,
                            OfficeNumber = 203
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 5,
                            Equipment = "[]",
                            FloorNumber = 1,
                            OfficeNumber = 204
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 20,
                            Equipment = "[]",
                            FloorNumber = 2,
                            OfficeNumber = 301
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 10,
                            Equipment = "[]",
                            FloorNumber = 2,
                            OfficeNumber = 302
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 8,
                            Equipment = "[]",
                            FloorNumber = 2,
                            OfficeNumber = 303
                        });
                });

            modelBuilder.Entity("OfficeBooker.Models.cs.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("OfficeBooker.Models.cs.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Piotr",
                            Surname = "Nowak"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aneta",
                            Surname = "Kowalska"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mateusz",
                            Surname = "Wiśniewski"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Karolina",
                            Surname = "Wójcik"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jakub",
                            Surname = "Kowalczyk"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Małgorzata",
                            Surname = "Kamińska"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wojciech",
                            Surname = "Lewandowski"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Katarzyna",
                            Surname = "Zielińska"
                        });
                });

            modelBuilder.Entity("OfficeBooker.Models.cs.Reservation", b =>
                {
                    b.HasOne("OfficeBooker.Models.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeBooker.Models.cs.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("Worker");
                });
#pragma warning restore 612, 618
        }
    }
}
